# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Шмэлькa | @hairpin01

from . import geek, inline_types, inline_utils, loader, proxies, security, utils
from . import translat as translations
from .config import ConfigValue, LibraryConfig, ModuleConfig
from .decorators import (
    InfiniteLoop,
    Placeholder,
    callback_handler,
    command,
    debug_method,
    inline_handler,
    loop,
    on,
    raw_handler,
    tag,
    tds,
    watcher,
)
from .fake_package import (
    _detect_module_type,
    _ensure_fake_package,
    _inject_module_alias,
    is_hikka_module,
    load_hikka_module,
    unload_hikka_module,
)
from .inline_types import (
    BotInlineCall,
    BotMessage,
    InlineCall,
    InlineMessage,
    InlineQuery,
    InlineResults,
    InlineUnit,
)
from .inline_utils import (
    VALID_BUTTON_STYLES,
    InlineMarkupBuilder,
    generate_markup,
    process_buttons,
    sanitise_text,
)
from .proxies import (
    PointerDict,
    PointerList,
    SafeAllModulesProxy,
    SafeClientProxy,
    SafeDatabaseProxy,
    SafeInlineProxy,
)
from .runtime import (
    DbProxy,
    InlineProxy,
    Library,
    Module,
    _AllModulesStub,
    _CallableStringsDict,
)
from .types import (
    CacheRecordEntity,
    CacheRecordFullChannel,
    CacheRecordFullUser,
    CacheRecordPerms,
    Command,
    CoreOverwriteError,
    CoreUnloadError,
    HerokuReplyMarkup,
    JSONSerializable,
    ListLike,
    LoadError,
    SelfSuspend,
    SelfUnload,
    StopLoop,
    StringLoader,
    get_callback_handlers,
    get_commands,
    get_inline_handlers,
    get_watchers,
)
from .validators import validators

__all__ = [
    "VALID_BUTTON_STYLES",
    "BotInlineCall",
    "BotMessage",
    "CacheRecordEntity",
    "CacheRecordFullChannel",
    "CacheRecordFullUser",
    "CacheRecordPerms",
    "Command",
    "ConfigValue",
    "CoreOverwriteError",
    "CoreUnloadError",
    "DbProxy",
    "HerokuReplyMarkup",
    "InfiniteLoop",
    "InlineCall",
    "InlineMarkupBuilder",
    "InlineMessage",
    "InlineProxy",
    "InlineQuery",
    "InlineResults",
    "InlineUnit",
    "JSONSerializable",
    "Library",
    "LibraryConfig",
    "ListLike",
    "LoadError",
    "Module",
    "ModuleConfig",
    "Placeholder",
    "PointerDict",
    "PointerList",
    "SafeAllModulesProxy",
    "SafeClientProxy",
    "SafeDatabaseProxy",
    "SafeInlineProxy",
    "SelfSuspend",
    "SelfUnload",
    "StopLoop",
    "StringLoader",
    "_AllModulesStub",
    "_CallableStringsDict",
    "_detect_module_type",
    "_ensure_fake_package",
    "_inject_module_alias",
    "callback_handler",
    "command",
    "debug_method",
    "geek",
    "generate_markup",
    "get_callback_handlers",
    "get_commands",
    "get_inline_handlers",
    "get_watchers",
    "inline_handler",
    "inline_utils",
    "loader",
    "loop",
    "on",
    "proxies",
    "raw_handler",
    "security",
    "tag",
    "tds",
    "translations",
    "utils",
    "validators",
    "watcher",
]
